services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  courses-manager:
    image: coursesmanager:latest
    build:
      context: ./Courses-Manager
      dockerfile: Dockerfile
    container_name: courses_manager_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MongoDBSettings__ConnectionString: "mongodb://admin:password@mongodb:27017"
      MongoDBSettings__DatabaseName: "CoursesDB"
    ports:
      - "5001:8080"

  students-manager:
    image: studentsmanager:latest
    build:
      context: ./Student-Manager
      dockerfile: Dockerfile
    container_name: students_manager_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MongoDBSettings__ConnectionString: "mongodb://admin:password@mongodb:27017"
      MongoDBSettings__DatabaseName: "StudentsDB"
    ports:
      - "5002:8080"

  instructors-manager:
    image: instructorsmanager:latest
    build:
      context: ./Instructor-Manager
      dockerfile: Dockerfile
    container_name: instructors_manager_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      MongoDBSettings__ConnectionString: "mongodb://admin:password@mongodb:27017"
      MongoDBSettings__DatabaseName: "InstructorsDB"
    ports:
      - "5003:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongo-data:
