using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace CoursesManager;

public class Course
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; } // Auto-generated by MongoDB

    [Required]
    public string? Title { get; set; }

    public string? Description { get; set; }

    [Required]
    public string? CourseCode { get; set; }

    public string? Language { get; set; }

    public string? Status { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int MaxStudents { get; set; }

    public List<string> Instructors { get; set; } = [];

    public List<string> Students { get; set; } = [];
}
